import pandas as pd
data = pd.read_csv("auto.csv")
data.fillna(0, inplace=True)
print("Most expensive car company:")
print(data[data.price == data.price.max()].company)
print("All Toyota cars:")
print(data[data.company == 'toyota'])
print("Total cars from each company:")
print(data.company.value_counts())
print("Highest priced car details:")
print(data.loc[data.price.idxmax()])
print("Average mileage per company:")
print(data.groupby('company')['average-mileage'].mean())
print("Cars sorted by price:")
print(data.sort_values(by='price'))